version: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: make
          command: cmake .. && make
          working_directory: ~/project/build
